# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FormEdit.ui'
#
# Created: Thu Aug 29 17:01:14 2019
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DialogFormEdit(object):
    def setupUi(self, DialogFormEdit):
        DialogFormEdit.setObjectName(_fromUtf8("DialogFormEdit"))
        DialogFormEdit.resize(940, 494)
        DialogFormEdit.setMaximumSize(QtCore.QSize(16777215, 494))
        DialogFormEdit.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.gridLayout = QtGui.QGridLayout(DialogFormEdit)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lbl_CDI = QtGui.QLabel(DialogFormEdit)
        self.lbl_CDI.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_CDI.setObjectName(_fromUtf8("lbl_CDI"))
        self.gridLayout.addWidget(self.lbl_CDI, 0, 0, 1, 1)
        self.lineEdit_CDI = QtGui.QLineEdit(DialogFormEdit)
        self.lineEdit_CDI.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.lineEdit_CDI.setObjectName(_fromUtf8("lineEdit_CDI"))
        self.gridLayout.addWidget(self.lineEdit_CDI, 0, 1, 1, 1)
        self.label_Datum_Horiz = QtGui.QLabel(DialogFormEdit)
        self.label_Datum_Horiz.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Datum_Horiz.setObjectName(_fromUtf8("label_Datum_Horiz"))
        self.gridLayout.addWidget(self.label_Datum_Horiz, 0, 2, 1, 1)
        self.textEdit_Datum_H = QtGui.QTextEdit(DialogFormEdit)
        self.textEdit_Datum_H.setMaximumSize(QtCore.QSize(16777215, 40))
        self.textEdit_Datum_H.setObjectName(_fromUtf8("textEdit_Datum_H"))
        self.gridLayout.addWidget(self.textEdit_Datum_H, 0, 3, 1, 1)
        self.label_Datum_Verti = QtGui.QLabel(DialogFormEdit)
        self.label_Datum_Verti.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Datum_Verti.setObjectName(_fromUtf8("label_Datum_Verti"))
        self.gridLayout.addWidget(self.label_Datum_Verti, 0, 4, 1, 1)
        self.textEdit_Datum_V = QtGui.QTextEdit(DialogFormEdit)
        self.textEdit_Datum_V.setMaximumSize(QtCore.QSize(16777215, 40))
        self.textEdit_Datum_V.setObjectName(_fromUtf8("textEdit_Datum_V"))
        self.gridLayout.addWidget(self.textEdit_Datum_V, 0, 5, 1, 1)
        self.label_Limite_W = QtGui.QLabel(DialogFormEdit)
        self.label_Limite_W.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Limite_W.setObjectName(_fromUtf8("label_Limite_W"))
        self.gridLayout.addWidget(self.label_Limite_W, 1, 0, 1, 1)
        self.lineEdit_Limite_W = QtGui.QLineEdit(DialogFormEdit)
        self.lineEdit_Limite_W.setMaximumSize(QtCore.QSize(16777215, 26))
        self.lineEdit_Limite_W.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.lineEdit_Limite_W.setObjectName(_fromUtf8("lineEdit_Limite_W"))
        self.gridLayout.addWidget(self.lineEdit_Limite_W, 1, 1, 1, 1)
        self.lineEdit_Limite_E = QtGui.QLineEdit(DialogFormEdit)
        self.lineEdit_Limite_E.setMaximumSize(QtCore.QSize(16777215, 26))
        self.lineEdit_Limite_E.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.lineEdit_Limite_E.setObjectName(_fromUtf8("lineEdit_Limite_E"))
        self.gridLayout.addWidget(self.lineEdit_Limite_E, 1, 2, 1, 1)
        self.label_Limite_N = QtGui.QLabel(DialogFormEdit)
        self.label_Limite_N.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Limite_N.setObjectName(_fromUtf8("label_Limite_N"))
        self.gridLayout.addWidget(self.label_Limite_N, 1, 3, 1, 1)
        self.lineEdit_Limite_N = QtGui.QLineEdit(DialogFormEdit)
        self.lineEdit_Limite_N.setMaximumSize(QtCore.QSize(16777215, 26))
        self.lineEdit_Limite_N.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.lineEdit_Limite_N.setObjectName(_fromUtf8("lineEdit_Limite_N"))
        self.gridLayout.addWidget(self.lineEdit_Limite_N, 1, 4, 1, 1)
        self.lineEdit_Limite_S = QtGui.QLineEdit(DialogFormEdit)
        self.lineEdit_Limite_S.setMaximumSize(QtCore.QSize(200, 26))
        self.lineEdit_Limite_S.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.lineEdit_Limite_S.setObjectName(_fromUtf8("lineEdit_Limite_S"))
        self.gridLayout.addWidget(self.lineEdit_Limite_S, 1, 5, 1, 1)
        self.label__Prof_Min = QtGui.QLabel(DialogFormEdit)
        self.label__Prof_Min.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label__Prof_Min.setObjectName(_fromUtf8("label__Prof_Min"))
        self.gridLayout.addWidget(self.label__Prof_Min, 2, 0, 1, 1)
        self.lineEdit_ProfMin = QtGui.QLineEdit(DialogFormEdit)
        self.lineEdit_ProfMin.setMaximumSize(QtCore.QSize(16777215, 26))
        self.lineEdit_ProfMin.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.lineEdit_ProfMin.setObjectName(_fromUtf8("lineEdit_ProfMin"))
        self.gridLayout.addWidget(self.lineEdit_ProfMin, 2, 1, 1, 1)
        self.lineEdit_ProfMax = QtGui.QLineEdit(DialogFormEdit)
        self.lineEdit_ProfMax.setMaximumSize(QtCore.QSize(16777215, 26))
        self.lineEdit_ProfMax.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.lineEdit_ProfMax.setObjectName(_fromUtf8("lineEdit_ProfMax"))
        self.gridLayout.addWidget(self.lineEdit_ProfMax, 2, 2, 1, 1)
        self.label_Data_ini = QtGui.QLabel(DialogFormEdit)
        self.label_Data_ini.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Data_ini.setObjectName(_fromUtf8("label_Data_ini"))
        self.gridLayout.addWidget(self.label_Data_ini, 2, 3, 1, 1)
        self.dateTimeEdit_Ini = QtGui.QDateTimeEdit(DialogFormEdit)
        self.dateTimeEdit_Ini.setMinimumSize(QtCore.QSize(0, 26))
        self.dateTimeEdit_Ini.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.dateTimeEdit_Ini.setObjectName(_fromUtf8("dateTimeEdit_Ini"))
        self.gridLayout.addWidget(self.dateTimeEdit_Ini, 2, 4, 1, 1)
        self.dateTimeEdit_Fim = QtGui.QDateTimeEdit(DialogFormEdit)
        self.dateTimeEdit_Fim.setMinimumSize(QtCore.QSize(0, 26))
        self.dateTimeEdit_Fim.setMaximumSize(QtCore.QSize(200, 16777215))
        self.dateTimeEdit_Fim.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.dateTimeEdit_Fim.setObjectName(_fromUtf8("dateTimeEdit_Fim"))
        self.gridLayout.addWidget(self.dateTimeEdit_Fim, 2, 5, 1, 1)
        self.label_Cruzeiro = QtGui.QLabel(DialogFormEdit)
        self.label_Cruzeiro.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Cruzeiro.setObjectName(_fromUtf8("label_Cruzeiro"))
        self.gridLayout.addWidget(self.label_Cruzeiro, 3, 0, 1, 1)
        self.lineEdit_Cruzeiro = QtGui.QLineEdit(DialogFormEdit)
        self.lineEdit_Cruzeiro.setMaximumSize(QtCore.QSize(16777215, 26))
        self.lineEdit_Cruzeiro.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.lineEdit_Cruzeiro.setObjectName(_fromUtf8("lineEdit_Cruzeiro"))
        self.gridLayout.addWidget(self.lineEdit_Cruzeiro, 3, 1, 1, 1)
        self.label_ID_Cruzeiro = QtGui.QLabel(DialogFormEdit)
        self.label_ID_Cruzeiro.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_ID_Cruzeiro.setObjectName(_fromUtf8("label_ID_Cruzeiro"))
        self.gridLayout.addWidget(self.label_ID_Cruzeiro, 3, 2, 1, 1)
        self.lineEdit_ID_Cruzeiro = QtGui.QLineEdit(DialogFormEdit)
        self.lineEdit_ID_Cruzeiro.setMaximumSize(QtCore.QSize(16777215, 26))
        self.lineEdit_ID_Cruzeiro.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.lineEdit_ID_Cruzeiro.setObjectName(_fromUtf8("lineEdit_ID_Cruzeiro"))
        self.gridLayout.addWidget(self.lineEdit_ID_Cruzeiro, 3, 3, 1, 1)
        self.label_Plataforma = QtGui.QLabel(DialogFormEdit)
        self.label_Plataforma.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Plataforma.setObjectName(_fromUtf8("label_Plataforma"))
        self.gridLayout.addWidget(self.label_Plataforma, 3, 4, 1, 1)
        self.comboBox_Plataforma = QtGui.QComboBox(DialogFormEdit)
        self.comboBox_Plataforma.setMaximumSize(QtCore.QSize(200, 16777215))
        self.comboBox_Plataforma.setObjectName(_fromUtf8("comboBox_Plataforma"))
        self.gridLayout.addWidget(self.comboBox_Plataforma, 3, 5, 1, 1)
        self.label_Resumo = QtGui.QLabel(DialogFormEdit)
        self.label_Resumo.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Resumo.setObjectName(_fromUtf8("label_Resumo"))
        self.gridLayout.addWidget(self.label_Resumo, 4, 0, 1, 1)
        self.label_Equipamentos = QtGui.QLabel(DialogFormEdit)
        self.label_Equipamentos.setObjectName(_fromUtf8("label_Equipamentos"))
        self.gridLayout.addWidget(self.label_Equipamentos, 5, 0, 1, 1)
        self.pushButtonAddEquip = QtGui.QPushButton(DialogFormEdit)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonAddEquip.sizePolicy().hasHeightForWidth())
        self.pushButtonAddEquip.setSizePolicy(sizePolicy)
        self.pushButtonAddEquip.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButtonAddEquip.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButtonAddEquip.setObjectName(_fromUtf8("pushButtonAddEquip"))
        self.gridLayout.addWidget(self.pushButtonAddEquip, 5, 1, 1, 1)
        self.label_Parametros = QtGui.QLabel(DialogFormEdit)
        self.label_Parametros.setObjectName(_fromUtf8("label_Parametros"))
        self.gridLayout.addWidget(self.label_Parametros, 5, 3, 1, 1)
        self.pushButtonAddParam = QtGui.QPushButton(DialogFormEdit)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonAddParam.sizePolicy().hasHeightForWidth())
        self.pushButtonAddParam.setSizePolicy(sizePolicy)
        self.pushButtonAddParam.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButtonAddParam.setObjectName(_fromUtf8("pushButtonAddParam"))
        self.gridLayout.addWidget(self.pushButtonAddParam, 5, 4, 1, 1)
        self.listWidget_Equip = QtGui.QListWidget(DialogFormEdit)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_Equip.sizePolicy().hasHeightForWidth())
        self.listWidget_Equip.setSizePolicy(sizePolicy)
        self.listWidget_Equip.setMinimumSize(QtCore.QSize(0, 27))
        self.listWidget_Equip.setMaximumSize(QtCore.QSize(16777215, 120))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(8)
        self.listWidget_Equip.setFont(font)
        self.listWidget_Equip.setObjectName(_fromUtf8("listWidget_Equip"))
        self.gridLayout.addWidget(self.listWidget_Equip, 6, 0, 1, 3)
        self.listWidget_Param = QtGui.QListWidget(DialogFormEdit)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_Param.sizePolicy().hasHeightForWidth())
        self.listWidget_Param.setSizePolicy(sizePolicy)
        self.listWidget_Param.setMinimumSize(QtCore.QSize(0, 27))
        self.listWidget_Param.setMaximumSize(QtCore.QSize(16777215, 120))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(8)
        self.listWidget_Param.setFont(font)
        self.listWidget_Param.setObjectName(_fromUtf8("listWidget_Param"))
        self.gridLayout.addWidget(self.listWidget_Param, 6, 3, 1, 3)
        self.label_Contacto = QtGui.QLabel(DialogFormEdit)
        self.label_Contacto.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Contacto.setObjectName(_fromUtf8("label_Contacto"))
        self.gridLayout.addWidget(self.label_Contacto, 7, 0, 1, 1)
        self.textEdit_Contacto = QtGui.QTextEdit(DialogFormEdit)
        self.textEdit_Contacto.setMaximumSize(QtCore.QSize(16777215, 40))
        self.textEdit_Contacto.setObjectName(_fromUtf8("textEdit_Contacto"))
        self.gridLayout.addWidget(self.textEdit_Contacto, 7, 1, 1, 1)
        self.label_Origem = QtGui.QLabel(DialogFormEdit)
        self.label_Origem.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Origem.setObjectName(_fromUtf8("label_Origem"))
        self.gridLayout.addWidget(self.label_Origem, 7, 2, 1, 1)
        self.textEdit_Origem = QtGui.QTextEdit(DialogFormEdit)
        self.textEdit_Origem.setMaximumSize(QtCore.QSize(16777215, 40))
        self.textEdit_Origem.setObjectName(_fromUtf8("textEdit_Origem"))
        self.gridLayout.addWidget(self.textEdit_Origem, 7, 3, 1, 1)
        self.label_Distribuidor = QtGui.QLabel(DialogFormEdit)
        self.label_Distribuidor.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Distribuidor.setObjectName(_fromUtf8("label_Distribuidor"))
        self.gridLayout.addWidget(self.label_Distribuidor, 7, 4, 1, 1)
        self.textEdit_Distributor = QtGui.QTextEdit(DialogFormEdit)
        self.textEdit_Distributor.setMaximumSize(QtCore.QSize(200, 40))
        self.textEdit_Distributor.setObjectName(_fromUtf8("textEdit_Distributor"))
        self.gridLayout.addWidget(self.textEdit_Distributor, 7, 5, 1, 1)
        self.label_Organizador = QtGui.QLabel(DialogFormEdit)
        self.label_Organizador.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Organizador.setObjectName(_fromUtf8("label_Organizador"))
        self.gridLayout.addWidget(self.label_Organizador, 8, 0, 1, 1)
        self.textEdit_Organizador = QtGui.QTextEdit(DialogFormEdit)
        self.textEdit_Organizador.setMaximumSize(QtCore.QSize(16777215, 40))
        self.textEdit_Organizador.setObjectName(_fromUtf8("textEdit_Organizador"))
        self.gridLayout.addWidget(self.textEdit_Organizador, 8, 1, 1, 1)
        self.label_Tamanho = QtGui.QLabel(DialogFormEdit)
        self.label_Tamanho.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Tamanho.setObjectName(_fromUtf8("label_Tamanho"))
        self.gridLayout.addWidget(self.label_Tamanho, 8, 2, 1, 1)
        self.lineEdit_Tamanho = QtGui.QLineEdit(DialogFormEdit)
        self.lineEdit_Tamanho.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEdit_Tamanho.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lineEdit_Tamanho.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.lineEdit_Tamanho.setObjectName(_fromUtf8("lineEdit_Tamanho"))
        self.gridLayout.addWidget(self.lineEdit_Tamanho, 8, 3, 1, 1)
        self.label_Acesso = QtGui.QLabel(DialogFormEdit)
        self.label_Acesso.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Acesso.setObjectName(_fromUtf8("label_Acesso"))
        self.gridLayout.addWidget(self.label_Acesso, 8, 4, 1, 1)
        self.comboBox_Acesso = QtGui.QComboBox(DialogFormEdit)
        self.comboBox_Acesso.setObjectName(_fromUtf8("comboBox_Acesso"))
        self.gridLayout.addWidget(self.comboBox_Acesso, 8, 5, 1, 1)
        self.label_QC = QtGui.QLabel(DialogFormEdit)
        self.label_QC.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.label_QC.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_QC.setObjectName(_fromUtf8("label_QC"))
        self.gridLayout.addWidget(self.label_QC, 9, 0, 1, 1)
        self.lineEdit_QC_Obs = QtGui.QLineEdit(DialogFormEdit)
        self.lineEdit_QC_Obs.setMinimumSize(QtCore.QSize(0, 27))
        self.lineEdit_QC_Obs.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.lineEdit_QC_Obs.setObjectName(_fromUtf8("lineEdit_QC_Obs"))
        self.gridLayout.addWidget(self.lineEdit_QC_Obs, 9, 3, 1, 1)
        self.label_QC_Feito = QtGui.QLabel(DialogFormEdit)
        self.label_QC_Feito.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_QC_Feito.setObjectName(_fromUtf8("label_QC_Feito"))
        self.gridLayout.addWidget(self.label_QC_Feito, 9, 4, 1, 1)
        self.comboBox_QC_Feito = QtGui.QComboBox(DialogFormEdit)
        self.comboBox_QC_Feito.setMinimumSize(QtCore.QSize(50, 25))
        self.comboBox_QC_Feito.setMaximumSize(QtCore.QSize(60, 16777215))
        self.comboBox_QC_Feito.setObjectName(_fromUtf8("comboBox_QC_Feito"))
        self.gridLayout.addWidget(self.comboBox_QC_Feito, 9, 5, 1, 1)
        self.label_Rev_Date = QtGui.QLabel(DialogFormEdit)
        self.label_Rev_Date.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.label_Rev_Date.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Rev_Date.setObjectName(_fromUtf8("label_Rev_Date"))
        self.gridLayout.addWidget(self.label_Rev_Date, 10, 0, 1, 1)
        self.dateEdit_Rev_Date = QtGui.QDateEdit(DialogFormEdit)
        self.dateEdit_Rev_Date.setObjectName(_fromUtf8("dateEdit_Rev_Date"))
        self.gridLayout.addWidget(self.dateEdit_Rev_Date, 10, 1, 1, 1)
        self.pushButton_Editar = QtGui.QPushButton(DialogFormEdit)
        self.pushButton_Editar.setObjectName(_fromUtf8("pushButton_Editar"))
        self.gridLayout.addWidget(self.pushButton_Editar, 11, 0, 1, 1)
        self.pushButton_Gravar = QtGui.QPushButton(DialogFormEdit)
        self.pushButton_Gravar.setObjectName(_fromUtf8("pushButton_Gravar"))
        self.gridLayout.addWidget(self.pushButton_Gravar, 11, 1, 1, 1)
        self.pushButton_Sair = QtGui.QPushButton(DialogFormEdit)
        self.pushButton_Sair.setObjectName(_fromUtf8("pushButton_Sair"))
        self.gridLayout.addWidget(self.pushButton_Sair, 11, 5, 1, 1)
        self.lineEdit_QC = QtGui.QLineEdit(DialogFormEdit)
        self.lineEdit_QC.setMinimumSize(QtCore.QSize(0, 27))
        self.lineEdit_QC.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.lineEdit_QC.setObjectName(_fromUtf8("lineEdit_QC"))
        self.gridLayout.addWidget(self.lineEdit_QC, 9, 1, 1, 2)
        self.lineEdit_Resumo = QtGui.QLineEdit(DialogFormEdit)
        self.lineEdit_Resumo.setMinimumSize(QtCore.QSize(0, 26))
        self.lineEdit_Resumo.setMaximumSize(QtCore.QSize(16777215, 26))
        self.lineEdit_Resumo.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Portugal))
        self.lineEdit_Resumo.setObjectName(_fromUtf8("lineEdit_Resumo"))
        self.gridLayout.addWidget(self.lineEdit_Resumo, 4, 1, 1, 5)

        self.retranslateUi(DialogFormEdit)
        QtCore.QObject.connect(self.pushButton_Sair, QtCore.SIGNAL(_fromUtf8("clicked()")), DialogFormEdit.close)
        QtCore.QMetaObject.connectSlotsByName(DialogFormEdit)

    def retranslateUi(self, DialogFormEdit):
        DialogFormEdit.setWindowTitle(_translate("DialogFormEdit", "Editar", None))
        self.lbl_CDI.setText(_translate("DialogFormEdit", "CDI:", None))
        self.label_Datum_Horiz.setText(_translate("DialogFormEdit", "Datum Horizonta (orig.):", None))
        self.label_Datum_Verti.setText(_translate("DialogFormEdit", "Datum Vertical (orig.):", None))
        self.label_Limite_W.setText(_translate("DialogFormEdit", "Limite W/E (WGS84 º ):", None))
        self.label_Limite_N.setText(_translate("DialogFormEdit", "Limite N/S:", None))
        self.label__Prof_Min.setText(_translate("DialogFormEdit", "Prof. Minima/Máx. (m LAT):", None))
        self.label_Data_ini.setText(_translate("DialogFormEdit", "Data Início/Fim:", None))
        self.label_Cruzeiro.setText(_translate("DialogFormEdit", "Nome do cruzeiro:", None))
        self.label_ID_Cruzeiro.setText(_translate("DialogFormEdit", "ID Cruzeiro:", None))
        self.label_Plataforma.setText(_translate("DialogFormEdit", "Plataforma:", None))
        self.label_Resumo.setText(_translate("DialogFormEdit", "Resumo:", None))
        self.label_Equipamentos.setText(_translate("DialogFormEdit", "Equipamentos:", None))
        self.pushButtonAddEquip.setText(_translate("DialogFormEdit", "Adicionar Equipamento", None))
        self.label_Parametros.setText(_translate("DialogFormEdit", "Parâmetros:", None))
        self.pushButtonAddParam.setText(_translate("DialogFormEdit", "Adicionar Parâmetro", None))
        self.label_Contacto.setText(_translate("DialogFormEdit", "Contacto:", None))
        self.label_Origem.setText(_translate("DialogFormEdit", "Origem:", None))
        self.label_Distribuidor.setText(_translate("DialogFormEdit", "Distribuidor:", None))
        self.label_Organizador.setText(_translate("DialogFormEdit", "Organizador:", None))
        self.label_Tamanho.setText(_translate("DialogFormEdit", "Tamanho (MB):", None))
        self.lineEdit_Tamanho.setToolTip(_translate("DialogFormEdit", "<html><head/><body><p>Valor inteiro (Mbytes)</p></body></html>", None))
        self.label_Acesso.setText(_translate("DialogFormEdit", "Acesso:", None))
        self.label_QC.setText(_translate("DialogFormEdit", "Controlo Qualidade/ Obs:", None))
        self.label_QC_Feito.setText(_translate("DialogFormEdit", "Efectuado:", None))
        self.label_Rev_Date.setText(_translate("DialogFormEdit", "Data revisão:", None))
        self.pushButton_Editar.setText(_translate("DialogFormEdit", "&Editar", None))
        self.pushButton_Gravar.setText(_translate("DialogFormEdit", "&Gravar", None))
        self.pushButton_Sair.setText(_translate("DialogFormEdit", "&Sair", None))

