# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FormImportFile.ui'
#
# Created: Mon Aug 29 00:18:08 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DialogImport(object):
    def setupUi(self, DialogImport):
        DialogImport.setObjectName(_fromUtf8("DialogImport"))
        DialogImport.resize(695, 384)
        DialogImport.setToolTip(_fromUtf8(""))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(DialogImport)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.labelFicheiro = QtGui.QLabel(DialogImport)
        self.labelFicheiro.setObjectName(_fromUtf8("labelFicheiro"))
        self.horizontalLayout.addWidget(self.labelFicheiro)
        self.lineEdit = QtGui.QLineEdit(DialogImport)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.textEdit = QtGui.QTextEdit(DialogImport)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setMinimumSize(QtCore.QSize(500, 120))
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.verticalLayout_2.addWidget(self.textEdit)
        self.label = QtGui.QLabel(DialogImport)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_3 = QtGui.QLabel(DialogImport)
        self.label_3.setMaximumSize(QtCore.QSize(30, 25))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_2.addWidget(self.label_3)
        self.cboX = QtGui.QComboBox(DialogImport)
        self.cboX.setMaximumSize(QtCore.QSize(40, 25))
        self.cboX.setObjectName(_fromUtf8("cboX"))
        self.horizontalLayout_2.addWidget(self.cboX)
        self.label_4 = QtGui.QLabel(DialogImport)
        self.label_4.setMaximumSize(QtCore.QSize(30, 25))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_2.addWidget(self.label_4)
        self.cboY = QtGui.QComboBox(DialogImport)
        self.cboY.setMaximumSize(QtCore.QSize(40, 25))
        self.cboY.setObjectName(_fromUtf8("cboY"))
        self.horizontalLayout_2.addWidget(self.cboY)
        self.label_5 = QtGui.QLabel(DialogImport)
        self.label_5.setMaximumSize(QtCore.QSize(30, 25))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_2.addWidget(self.label_5)
        self.cboZ = QtGui.QComboBox(DialogImport)
        self.cboZ.setMaximumSize(QtCore.QSize(40, 25))
        self.cboZ.setObjectName(_fromUtf8("cboZ"))
        self.horizontalLayout_2.addWidget(self.cboZ)
        self.label_6 = QtGui.QLabel(DialogImport)
        self.label_6.setMaximumSize(QtCore.QSize(20, 25))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_2.addWidget(self.label_6)
        self.cboReflect = QtGui.QComboBox(DialogImport)
        self.cboReflect.setMaximumSize(QtCore.QSize(40, 25))
        self.cboReflect.setObjectName(_fromUtf8("cboReflect"))
        self.horizontalLayout_2.addWidget(self.cboReflect)
        self.label_7 = QtGui.QLabel(DialogImport)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMaximumSize(QtCore.QSize(20, 25))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_2.addWidget(self.label_7)
        self.cboR = QtGui.QComboBox(DialogImport)
        self.cboR.setMaximumSize(QtCore.QSize(30, 16777215))
        self.cboR.setObjectName(_fromUtf8("cboR"))
        self.horizontalLayout_2.addWidget(self.cboR)
        self.label_9 = QtGui.QLabel(DialogImport)
        self.label_9.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_2.addWidget(self.label_9)
        self.cboG = QtGui.QComboBox(DialogImport)
        self.cboG.setMaximumSize(QtCore.QSize(30, 25))
        self.cboG.setObjectName(_fromUtf8("cboG"))
        self.horizontalLayout_2.addWidget(self.cboG)
        self.label_10 = QtGui.QLabel(DialogImport)
        self.label_10.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_2.addWidget(self.label_10)
        self.cboB = QtGui.QComboBox(DialogImport)
        self.cboB.setMaximumSize(QtCore.QSize(30, 16777215))
        self.cboB.setObjectName(_fromUtf8("cboB"))
        self.horizontalLayout_2.addWidget(self.cboB)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.plainTextEdit = QtGui.QPlainTextEdit(DialogImport)
        self.plainTextEdit.setMaximumSize(QtCore.QSize(200, 25))
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.gridLayout.addWidget(self.plainTextEdit, 0, 2, 1, 1)
        self.cboDatumHz = QtGui.QComboBox(DialogImport)
        self.cboDatumHz.setObjectName(_fromUtf8("cboDatumHz"))
        self.cboDatumHz.addItem(_fromUtf8(""))
        self.cboDatumHz.addItem(_fromUtf8(""))
        self.cboDatumHz.addItem(_fromUtf8(""))
        self.cboDatumHz.addItem(_fromUtf8(""))
        self.cboDatumHz.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cboDatumHz, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(DialogImport)
        self.label_2.setMaximumSize(QtCore.QSize(60, 20))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.cboDatumVert = QtGui.QComboBox(DialogImport)
        self.cboDatumVert.setObjectName(_fromUtf8("cboDatumVert"))
        self.cboDatumVert.addItem(_fromUtf8(""))
        self.cboDatumVert.addItem(_fromUtf8(""))
        self.cboDatumVert.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cboDatumVert, 2, 0, 1, 1)
        self.importButton = QtGui.QPushButton(DialogImport)
        self.importButton.setMaximumSize(QtCore.QSize(80, 16777215))
        self.importButton.setObjectName(_fromUtf8("importButton"))
        self.gridLayout.addWidget(self.importButton, 2, 2, 1, 1)
        self.convertButton = QtGui.QPushButton(DialogImport)
        self.convertButton.setMinimumSize(QtCore.QSize(80, 0))
        self.convertButton.setMaximumSize(QtCore.QSize(80, 16777215))
        self.convertButton.setObjectName(_fromUtf8("convertButton"))
        self.gridLayout.addWidget(self.convertButton, 1, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.pushButtonAbrirFicheiro = QtGui.QPushButton(DialogImport)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonAbrirFicheiro.sizePolicy().hasHeightForWidth())
        self.pushButtonAbrirFicheiro.setSizePolicy(sizePolicy)
        self.pushButtonAbrirFicheiro.setMaximumSize(QtCore.QSize(40, 23))
        self.pushButtonAbrirFicheiro.setObjectName(_fromUtf8("pushButtonAbrirFicheiro"))
        self.gridLayout_2.addWidget(self.pushButtonAbrirFicheiro, 0, 0, 1, 2, QtCore.Qt.AlignLeft)
        self.label_8 = QtGui.QLabel(DialogImport)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 1, 0, 1, 1)
        self.cboSep = QtGui.QComboBox(DialogImport)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboSep.sizePolicy().hasHeightForWidth())
        self.cboSep.setSizePolicy(sizePolicy)
        self.cboSep.setMinimumSize(QtCore.QSize(100, 0))
        self.cboSep.setMaximumSize(QtCore.QSize(100, 20))
        self.cboSep.setObjectName(_fromUtf8("cboSep"))
        self.cboSep.addItem(_fromUtf8(""))
        self.cboSep.setItemText(0, _fromUtf8(""))
        self.cboSep.addItem(_fromUtf8(""))
        self.cboSep.addItem(_fromUtf8(""))
        self.cboSep.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cboSep, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        spacerItem = QtGui.QSpacerItem(155, 177, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.okButton = QtGui.QPushButton(DialogImport)
        self.okButton.setObjectName(_fromUtf8("okButton"))
        self.horizontalLayout_3.addWidget(self.okButton)
        self.sairButton = QtGui.QPushButton(DialogImport)
        self.sairButton.setObjectName(_fromUtf8("sairButton"))
        self.horizontalLayout_3.addWidget(self.sairButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.actionSair = QtGui.QAction(DialogImport)
        self.actionSair.setObjectName(_fromUtf8("actionSair"))

        self.retranslateUi(DialogImport)
        self.cboSep.setCurrentIndex(2)
        QtCore.QObject.connect(self.sairButton, QtCore.SIGNAL(_fromUtf8("clicked()")), DialogImport.close)
        QtCore.QObject.connect(self.okButton, QtCore.SIGNAL(_fromUtf8("clicked()")), DialogImport.close)
        QtCore.QObject.connect(self.cboX, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(QString)")), self.plainTextEdit.appendPlainText)
        QtCore.QMetaObject.connectSlotsByName(DialogImport)

    def retranslateUi(self, DialogImport):
        DialogImport.setWindowTitle(_translate("DialogImport", "Importar dados xyz", None))
        self.labelFicheiro.setText(_translate("DialogImport", "Ficheiro a ler:", None))
        self.label.setText(_translate("DialogImport", "Escolha as colunas para cada tipo de dados:", None))
        self.label_3.setText(_translate("DialogImport", "X:", None))
        self.cboX.setToolTip(_translate("DialogImport", "<html><head/><body><p>Nº Colun -&gt; Coord. X</p></body></html>", None))
        self.label_4.setText(_translate("DialogImport", "Y:", None))
        self.cboY.setToolTip(_translate("DialogImport", "<html><head/><body><p>Nº Colun -&gt; Coord. Y</p></body></html>", None))
        self.label_5.setText(_translate("DialogImport", "Z:", None))
        self.cboZ.setToolTip(_translate("DialogImport", "<html><head/><body><p>Nº Colun -&gt; Prof </p></body></html>", None))
        self.label_6.setText(_translate("DialogImport", "Ref:", None))
        self.label_7.setText(_translate("DialogImport", "R:", None))
        self.label_9.setText(_translate("DialogImport", "G:", None))
        self.label_10.setText(_translate("DialogImport", "B:", None))
        self.cboDatumHz.setItemText(0, _translate("DialogImport", "Datum 73 (m)", None))
        self.cboDatumHz.setItemText(1, _translate("DialogImport", "Datum Lx (m)", None))
        self.cboDatumHz.setItemText(2, _translate("DialogImport", "ETRS89_pt_tm06 (m)", None))
        self.cboDatumHz.setItemText(3, _translate("DialogImport", "WGS84_UTM (m)", None))
        self.cboDatumHz.setItemText(4, _translate("DialogImport", "WGS84 LL (º)", None))
        self.label_2.setText(_translate("DialogImport", "CDI/CPRD :", None))
        self.cboDatumVert.setItemText(0, _translate("DialogImport", "Zero Hidrográfico", None))
        self.cboDatumVert.setItemText(1, _translate("DialogImport", "Nivel Médio do Mar", None))
        self.cboDatumVert.setItemText(2, _translate("DialogImport", "Elipsoide WGS84", None))
        self.importButton.setText(_translate("DialogImport", "Importar", None))
        self.convertButton.setText(_translate("DialogImport", "Conv.WGS84", None))
        self.pushButtonAbrirFicheiro.setText(_translate("DialogImport", "...", None))
        self.label_8.setText(_translate("DialogImport", "Separador", None))
        self.cboSep.setItemText(1, _translate("DialogImport", "SPACE", None))
        self.cboSep.setItemText(2, _translate("DialogImport", ",", None))
        self.cboSep.setItemText(3, _translate("DialogImport", ";", None))
        self.okButton.setText(_translate("DialogImport", "&Ok", None))
        self.sairButton.setText(_translate("DialogImport", "&Cancel", None))
        self.actionSair.setText(_translate("DialogImport", "sair", None))
        self.actionSair.setToolTip(_translate("DialogImport", "Sair", None))

