# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FormImportFile.ui'
#
# Created: Mon Jan 30 23:56:45 2017
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DialogImport(object):
    def setupUi(self, DialogImport):
        DialogImport.setObjectName(_fromUtf8("DialogImport"))
        DialogImport.resize(1068, 798)
        DialogImport.setToolTip(_fromUtf8(""))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(DialogImport)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.labelFicheiro = QtGui.QLabel(DialogImport)
        self.labelFicheiro.setObjectName(_fromUtf8("labelFicheiro"))
        self.horizontalLayout.addWidget(self.labelFicheiro)
        self.lineEdit = QtGui.QLineEdit(DialogImport)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.horizontalLayout.addWidget(self.lineEdit)
        self.pushButtonAbrirFicheiro = QtGui.QPushButton(DialogImport)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonAbrirFicheiro.sizePolicy().hasHeightForWidth())
        self.pushButtonAbrirFicheiro.setSizePolicy(sizePolicy)
        self.pushButtonAbrirFicheiro.setMaximumSize(QtCore.QSize(40, 23))
        self.pushButtonAbrirFicheiro.setObjectName(_fromUtf8("pushButtonAbrirFicheiro"))
        self.horizontalLayout.addWidget(self.pushButtonAbrirFicheiro)
        spacerItem = QtGui.QSpacerItem(368, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.checkBox_primeira_linha = QtGui.QCheckBox(DialogImport)
        self.checkBox_primeira_linha.setObjectName(_fromUtf8("checkBox_primeira_linha"))
        self.horizontalLayout.addWidget(self.checkBox_primeira_linha)
        self.label_8 = QtGui.QLabel(DialogImport)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout.addWidget(self.label_8)
        self.cboSep = QtGui.QComboBox(DialogImport)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboSep.sizePolicy().hasHeightForWidth())
        self.cboSep.setSizePolicy(sizePolicy)
        self.cboSep.setMinimumSize(QtCore.QSize(50, 0))
        self.cboSep.setMaximumSize(QtCore.QSize(50, 20))
        self.cboSep.setObjectName(_fromUtf8("cboSep"))
        self.cboSep.addItem(_fromUtf8(""))
        self.cboSep.setItemText(0, _fromUtf8(""))
        self.cboSep.addItem(_fromUtf8(""))
        self.cboSep.addItem(_fromUtf8(""))
        self.cboSep.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.cboSep)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.textEdit = QtGui.QTextEdit(DialogImport)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setMinimumSize(QtCore.QSize(0, 120))
        self.textEdit.setMaximumSize(QtCore.QSize(1200, 160))
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.verticalLayout.addWidget(self.textEdit)
        self.label = QtGui.QLabel(DialogImport)
        self.label.setMinimumSize(QtCore.QSize(0, 26))
        self.label.setMaximumSize(QtCore.QSize(16777215, 26))
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_3 = QtGui.QLabel(DialogImport)
        self.label_3.setMaximumSize(QtCore.QSize(15, 25))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_2.addWidget(self.label_3)
        self.cboX = QtGui.QComboBox(DialogImport)
        self.cboX.setMaximumSize(QtCore.QSize(40, 25))
        self.cboX.setObjectName(_fromUtf8("cboX"))
        self.horizontalLayout_2.addWidget(self.cboX)
        self.label_4 = QtGui.QLabel(DialogImport)
        self.label_4.setMaximumSize(QtCore.QSize(15, 25))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_2.addWidget(self.label_4)
        self.cboY = QtGui.QComboBox(DialogImport)
        self.cboY.setMaximumSize(QtCore.QSize(40, 25))
        self.cboY.setObjectName(_fromUtf8("cboY"))
        self.horizontalLayout_2.addWidget(self.cboY)
        self.label_5 = QtGui.QLabel(DialogImport)
        self.label_5.setMinimumSize(QtCore.QSize(15, 0))
        self.label_5.setMaximumSize(QtCore.QSize(15, 25))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_2.addWidget(self.label_5)
        self.cboZ = QtGui.QComboBox(DialogImport)
        self.cboZ.setMaximumSize(QtCore.QSize(40, 25))
        self.cboZ.setObjectName(_fromUtf8("cboZ"))
        self.horizontalLayout_2.addWidget(self.cboZ)
        self.label_6 = QtGui.QLabel(DialogImport)
        self.label_6.setMinimumSize(QtCore.QSize(40, 0))
        self.label_6.setMaximumSize(QtCore.QSize(40, 25))
        self.label_6.setFrameShadow(QtGui.QFrame.Plain)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_2.addWidget(self.label_6)
        self.cboReflect = QtGui.QComboBox(DialogImport)
        self.cboReflect.setMaximumSize(QtCore.QSize(40, 25))
        self.cboReflect.setObjectName(_fromUtf8("cboReflect"))
        self.horizontalLayout_2.addWidget(self.cboReflect)
        self.label_7 = QtGui.QLabel(DialogImport)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMaximumSize(QtCore.QSize(15, 25))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_2.addWidget(self.label_7)
        self.cboR = QtGui.QComboBox(DialogImport)
        self.cboR.setMaximumSize(QtCore.QSize(30, 16777215))
        self.cboR.setObjectName(_fromUtf8("cboR"))
        self.horizontalLayout_2.addWidget(self.cboR)
        self.label_9 = QtGui.QLabel(DialogImport)
        self.label_9.setMaximumSize(QtCore.QSize(15, 16777215))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_2.addWidget(self.label_9)
        self.cboG = QtGui.QComboBox(DialogImport)
        self.cboG.setMaximumSize(QtCore.QSize(30, 25))
        self.cboG.setObjectName(_fromUtf8("cboG"))
        self.horizontalLayout_2.addWidget(self.cboG)
        self.label_10 = QtGui.QLabel(DialogImport)
        self.label_10.setMaximumSize(QtCore.QSize(15, 16777215))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_2.addWidget(self.label_10)
        self.cboB = QtGui.QComboBox(DialogImport)
        self.cboB.setMaximumSize(QtCore.QSize(30, 16777215))
        self.cboB.setObjectName(_fromUtf8("cboB"))
        self.horizontalLayout_2.addWidget(self.cboB)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.groupBox = QtGui.QGroupBox(DialogImport)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 26))
        self.groupBox_2.setTitle(_fromUtf8(""))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.radioButton_pos = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_pos.setGeometry(QtCore.QRect(10, 3, 51, 20))
        self.radioButton_pos.setObjectName(_fromUtf8("radioButton_pos"))
        self.radioButton_neg = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_neg.setGeometry(QtCore.QRect(80, 3, 61, 20))
        self.radioButton_neg.setObjectName(_fromUtf8("radioButton_neg"))
        self.gridLayout.addWidget(self.groupBox_2, 11, 1, 1, 1)
        self.label_23 = QtGui.QLabel(self.groupBox)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout.addWidget(self.label_23, 9, 2, 1, 1, QtCore.Qt.AlignRight)
        self.label_12 = QtGui.QLabel(self.groupBox)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 11, 0, 1, 1)
        self.lineEdit_Obs = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_Obs.setMinimumSize(QtCore.QSize(0, 27))
        self.lineEdit_Obs.setObjectName(_fromUtf8("lineEdit_Obs"))
        self.gridLayout.addWidget(self.lineEdit_Obs, 10, 4, 1, 1)
        self.lineEdit_Esp = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_Esp.setMinimumSize(QtCore.QSize(0, 27))
        self.lineEdit_Esp.setObjectName(_fromUtf8("lineEdit_Esp"))
        self.gridLayout.addWidget(self.lineEdit_Esp, 11, 3, 1, 1)
        self.comboBox_Acesso = QtGui.QComboBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_Acesso.sizePolicy().hasHeightForWidth())
        self.comboBox_Acesso.setSizePolicy(sizePolicy)
        self.comboBox_Acesso.setMinimumSize(QtCore.QSize(0, 25))
        self.comboBox_Acesso.setObjectName(_fromUtf8("comboBox_Acesso"))
        self.gridLayout.addWidget(self.comboBox_Acesso, 9, 3, 1, 1)
        self.lineEdit_QC = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_QC.setMinimumSize(QtCore.QSize(0, 27))
        self.lineEdit_QC.setObjectName(_fromUtf8("lineEdit_QC"))
        self.gridLayout.addWidget(self.lineEdit_QC, 10, 1, 1, 3)
        self.label_13 = QtGui.QLabel(self.groupBox)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout.addWidget(self.label_13, 11, 2, 1, 1)
        self.comboBox_Feito = QtGui.QComboBox(self.groupBox)
        self.comboBox_Feito.setMinimumSize(QtCore.QSize(50, 25))
        self.comboBox_Feito.setMaximumSize(QtCore.QSize(60, 16777215))
        self.comboBox_Feito.setObjectName(_fromUtf8("comboBox_Feito"))
        self.gridLayout.addWidget(self.comboBox_Feito, 10, 5, 1, 1)
        self.checkBoxLong = QtGui.QCheckBox(self.groupBox)
        self.checkBoxLong.setMinimumSize(QtCore.QSize(0, 26))
        self.checkBoxLong.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBoxLong.setChecked(True)
        self.checkBoxLong.setObjectName(_fromUtf8("checkBoxLong"))
        self.gridLayout.addWidget(self.checkBoxLong, 1, 0, 1, 1)
        self.lineEdit_Distrib = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_Distrib.setMinimumSize(QtCore.QSize(0, 27))
        self.lineEdit_Distrib.setObjectName(_fromUtf8("lineEdit_Distrib"))
        self.gridLayout.addWidget(self.lineEdit_Distrib, 8, 1, 1, 2)
        self.label_21 = QtGui.QLabel(self.groupBox)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout.addWidget(self.label_21, 8, 0, 1, 1)
        self.lineEdit_LongW = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_LongW.setMinimumSize(QtCore.QSize(0, 26))
        self.lineEdit_LongW.setObjectName(_fromUtf8("lineEdit_LongW"))
        self.gridLayout.addWidget(self.lineEdit_LongW, 1, 1, 1, 1)
        self.label_25 = QtGui.QLabel(self.groupBox)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout.addWidget(self.label_25, 10, 0, 1, 1)
        self.label_20 = QtGui.QLabel(self.groupBox)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout.addWidget(self.label_20, 7, 0, 1, 1)
        self.label_17 = QtGui.QLabel(self.groupBox)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout.addWidget(self.label_17, 4, 0, 1, 1)
        self.label_22 = QtGui.QLabel(self.groupBox)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout.addWidget(self.label_22, 9, 0, 1, 1)
        self.lineEdit_Contacto = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_Contacto.setMinimumSize(QtCore.QSize(0, 27))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_Contacto.setFont(font)
        self.lineEdit_Contacto.setObjectName(_fromUtf8("lineEdit_Contacto"))
        self.gridLayout.addWidget(self.lineEdit_Contacto, 7, 1, 1, 2)
        self.lineEdit_Tamanho = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_Tamanho.setMinimumSize(QtCore.QSize(0, 27))
        self.lineEdit_Tamanho.setMaximumSize(QtCore.QSize(16777215, 16777212))
        self.lineEdit_Tamanho.setObjectName(_fromUtf8("lineEdit_Tamanho"))
        self.gridLayout.addWidget(self.lineEdit_Tamanho, 9, 1, 1, 1)
        self.lineEdit_LongE = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_LongE.setMinimumSize(QtCore.QSize(0, 26))
        self.lineEdit_LongE.setObjectName(_fromUtf8("lineEdit_LongE"))
        self.gridLayout.addWidget(self.lineEdit_LongE, 1, 2, 1, 1)
        self.pushButtonAddEquip = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonAddEquip.sizePolicy().hasHeightForWidth())
        self.pushButtonAddEquip.setSizePolicy(sizePolicy)
        self.pushButtonAddEquip.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButtonAddEquip.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButtonAddEquip.setObjectName(_fromUtf8("pushButtonAddEquip"))
        self.gridLayout.addWidget(self.pushButtonAddEquip, 5, 1, 1, 2)
        self.cboDatumVert = QtGui.QComboBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboDatumVert.sizePolicy().hasHeightForWidth())
        self.cboDatumVert.setSizePolicy(sizePolicy)
        self.cboDatumVert.setMinimumSize(QtCore.QSize(0, 26))
        self.cboDatumVert.setObjectName(_fromUtf8("cboDatumVert"))
        self.cboDatumVert.addItem(_fromUtf8(""))
        self.cboDatumVert.addItem(_fromUtf8(""))
        self.cboDatumVert.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cboDatumVert, 0, 4, 1, 1)
        self.lineEdit_cdi = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_cdi.sizePolicy().hasHeightForWidth())
        self.lineEdit_cdi.setSizePolicy(sizePolicy)
        self.lineEdit_cdi.setMinimumSize(QtCore.QSize(0, 26))
        self.lineEdit_cdi.setObjectName(_fromUtf8("lineEdit_cdi"))
        self.gridLayout.addWidget(self.lineEdit_cdi, 0, 1, 1, 1)
        self.cboDatumHz = QtGui.QComboBox(self.groupBox)
        self.cboDatumHz.setMinimumSize(QtCore.QSize(0, 26))
        self.cboDatumHz.setObjectName(_fromUtf8("cboDatumHz"))
        self.gridLayout.addWidget(self.cboDatumHz, 0, 3, 1, 1)
        self.label_24 = QtGui.QLabel(self.groupBox)
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout.addWidget(self.label_24, 2, 3, 1, 1)
        self.label_16 = QtGui.QLabel(self.groupBox)
        self.label_16.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout.addWidget(self.label_16, 1, 3, 1, 1)
        self.dateTimeEdit_Fim = QtGui.QDateTimeEdit(self.groupBox)
        self.dateTimeEdit_Fim.setMinimumSize(QtCore.QSize(0, 26))
        self.dateTimeEdit_Fim.setObjectName(_fromUtf8("dateTimeEdit_Fim"))
        self.gridLayout.addWidget(self.dateTimeEdit_Fim, 1, 5, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupBox)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 0, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setMaximumSize(QtCore.QSize(160, 20))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.dateTimeEdit_Ini = QtGui.QDateTimeEdit(self.groupBox)
        self.dateTimeEdit_Ini.setMinimumSize(QtCore.QSize(0, 26))
        self.dateTimeEdit_Ini.setObjectName(_fromUtf8("dateTimeEdit_Ini"))
        self.gridLayout.addWidget(self.dateTimeEdit_Ini, 1, 4, 1, 1)
        self.label_32 = QtGui.QLabel(self.groupBox)
        self.label_32.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_32.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout.addWidget(self.label_32, 3, 3, 1, 1)
        self.lineEdit_Cruzeiro = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Cruzeiro.sizePolicy().hasHeightForWidth())
        self.lineEdit_Cruzeiro.setSizePolicy(sizePolicy)
        self.lineEdit_Cruzeiro.setMinimumSize(QtCore.QSize(0, 27))
        self.lineEdit_Cruzeiro.setObjectName(_fromUtf8("lineEdit_Cruzeiro"))
        self.gridLayout.addWidget(self.lineEdit_Cruzeiro, 2, 4, 1, 1)
        self.checkBoxProf = QtGui.QCheckBox(self.groupBox)
        self.checkBoxProf.setMinimumSize(QtCore.QSize(0, 26))
        self.checkBoxProf.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBoxProf.setChecked(True)
        self.checkBoxProf.setObjectName(_fromUtf8("checkBoxProf"))
        self.gridLayout.addWidget(self.checkBoxProf, 3, 0, 1, 1)
        self.checkBoxLLat = QtGui.QCheckBox(self.groupBox)
        self.checkBoxLLat.setMinimumSize(QtCore.QSize(0, 26))
        self.checkBoxLLat.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBoxLLat.setChecked(True)
        self.checkBoxLLat.setObjectName(_fromUtf8("checkBoxLLat"))
        self.gridLayout.addWidget(self.checkBoxLLat, 2, 0, 1, 1)
        self.lineEdit_LatS = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_LatS.sizePolicy().hasHeightForWidth())
        self.lineEdit_LatS.setSizePolicy(sizePolicy)
        self.lineEdit_LatS.setMinimumSize(QtCore.QSize(0, 26))
        self.lineEdit_LatS.setObjectName(_fromUtf8("lineEdit_LatS"))
        self.gridLayout.addWidget(self.lineEdit_LatS, 2, 2, 1, 1)
        self.lineEdit_LatN = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_LatN.setMinimumSize(QtCore.QSize(0, 26))
        self.lineEdit_LatN.setObjectName(_fromUtf8("lineEdit_LatN"))
        self.gridLayout.addWidget(self.lineEdit_LatN, 2, 1, 1, 1)
        self.lineEdit_Origem = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_Origem.setMinimumSize(QtCore.QSize(0, 27))
        self.lineEdit_Origem.setObjectName(_fromUtf8("lineEdit_Origem"))
        self.gridLayout.addWidget(self.lineEdit_Origem, 7, 3, 1, 2)
        self.lineEdit_Resumo = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_Resumo.setMinimumSize(QtCore.QSize(0, 26))
        self.lineEdit_Resumo.setObjectName(_fromUtf8("lineEdit_Resumo"))
        self.gridLayout.addWidget(self.lineEdit_Resumo, 4, 1, 1, 5)
        self.lineEdit_ProfMax = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_ProfMax.setMinimumSize(QtCore.QSize(0, 26))
        self.lineEdit_ProfMax.setObjectName(_fromUtf8("lineEdit_ProfMax"))
        self.gridLayout.addWidget(self.lineEdit_ProfMax, 3, 1, 1, 1)
        self.lineEdit_Org = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_Org.setMinimumSize(QtCore.QSize(0, 27))
        self.lineEdit_Org.setObjectName(_fromUtf8("lineEdit_Org"))
        self.gridLayout.addWidget(self.lineEdit_Org, 8, 3, 1, 2)
        self.listWidgetParam = QtGui.QListWidget(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidgetParam.sizePolicy().hasHeightForWidth())
        self.listWidgetParam.setSizePolicy(sizePolicy)
        self.listWidgetParam.setMinimumSize(QtCore.QSize(0, 27))
        self.listWidgetParam.setMaximumSize(QtCore.QSize(16777215, 120))
        self.listWidgetParam.setObjectName(_fromUtf8("listWidgetParam"))
        self.gridLayout.addWidget(self.listWidgetParam, 6, 3, 1, 2)
        self.pushButtonAddParam = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonAddParam.sizePolicy().hasHeightForWidth())
        self.pushButtonAddParam.setSizePolicy(sizePolicy)
        self.pushButtonAddParam.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButtonAddParam.setObjectName(_fromUtf8("pushButtonAddParam"))
        self.gridLayout.addWidget(self.pushButtonAddParam, 5, 3, 1, 2)
        self.lineEdit_ProfMin = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_ProfMin.setMinimumSize(QtCore.QSize(0, 26))
        self.lineEdit_ProfMin.setObjectName(_fromUtf8("lineEdit_ProfMin"))
        self.gridLayout.addWidget(self.lineEdit_ProfMin, 3, 2, 1, 1)
        self.listWidget_Equip = QtGui.QListWidget(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_Equip.sizePolicy().hasHeightForWidth())
        self.listWidget_Equip.setSizePolicy(sizePolicy)
        self.listWidget_Equip.setMinimumSize(QtCore.QSize(0, 27))
        self.listWidget_Equip.setMaximumSize(QtCore.QSize(16777215, 120))
        self.listWidget_Equip.setObjectName(_fromUtf8("listWidget_Equip"))
        self.gridLayout.addWidget(self.listWidget_Equip, 6, 1, 1, 2)
        self.comboBox_Plataf = QtGui.QComboBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_Plataf.sizePolicy().hasHeightForWidth())
        self.comboBox_Plataf.setSizePolicy(sizePolicy)
        self.comboBox_Plataf.setMinimumSize(QtCore.QSize(0, 26))
        self.comboBox_Plataf.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.comboBox_Plataf.setObjectName(_fromUtf8("comboBox_Plataf"))
        self.gridLayout.addWidget(self.comboBox_Plataf, 3, 4, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.sairButton = QtGui.QPushButton(DialogImport)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sairButton.sizePolicy().hasHeightForWidth())
        self.sairButton.setSizePolicy(sizePolicy)
        self.sairButton.setMinimumSize(QtCore.QSize(80, 0))
        self.sairButton.setObjectName(_fromUtf8("sairButton"))
        self.horizontalLayout_3.addWidget(self.sairButton, QtCore.Qt.AlignRight)
        self.importButton = QtGui.QPushButton(DialogImport)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.importButton.sizePolicy().hasHeightForWidth())
        self.importButton.setSizePolicy(sizePolicy)
        self.importButton.setMinimumSize(QtCore.QSize(80, 0))
        self.importButton.setMaximumSize(QtCore.QSize(80, 16777215))
        self.importButton.setObjectName(_fromUtf8("importButton"))
        self.horizontalLayout_3.addWidget(self.importButton, QtCore.Qt.AlignRight)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.actionSair = QtGui.QAction(DialogImport)
        self.actionSair.setObjectName(_fromUtf8("actionSair"))
        self.labelFicheiro.setBuddy(self.lineEdit)
        self.label_8.setBuddy(self.cboSep)
        self.label_3.setBuddy(self.cboX)
        self.label_4.setBuddy(self.cboY)
        self.label_5.setBuddy(self.cboZ)
        self.label_6.setBuddy(self.cboReflect)
        self.label_7.setBuddy(self.cboR)
        self.label_9.setBuddy(self.cboG)
        self.label_10.setBuddy(self.cboB)
        self.label_23.setBuddy(self.comboBox_Acesso)
        self.label_21.setBuddy(self.lineEdit_Distrib)
        self.label_25.setBuddy(self.lineEdit_QC)
        self.label_20.setBuddy(self.lineEdit_Contacto)
        self.label_17.setBuddy(self.lineEdit_Resumo)
        self.label_22.setBuddy(self.lineEdit_Tamanho)
        self.label_24.setBuddy(self.lineEdit_Cruzeiro)
        self.label_16.setBuddy(self.dateTimeEdit_Ini)
        self.label_11.setBuddy(self.cboDatumHz)
        self.label_2.setBuddy(self.lineEdit_cdi)
        self.label_32.setBuddy(self.comboBox_Plataf)

        self.retranslateUi(DialogImport)
        self.cboSep.setCurrentIndex(2)
        QtCore.QObject.connect(self.sairButton, QtCore.SIGNAL(_fromUtf8("clicked()")), DialogImport.close)
        QtCore.QMetaObject.connectSlotsByName(DialogImport)

    def retranslateUi(self, DialogImport):
        DialogImport.setWindowTitle(_translate("DialogImport", "Importar dados xyz", None))
        self.labelFicheiro.setText(_translate("DialogImport", "Ficheiro a ler:", None))
        self.pushButtonAbrirFicheiro.setText(_translate("DialogImport", "...", None))
        self.checkBox_primeira_linha.setText(_translate("DialogImport", "&Ignorar 1ª linha     ", None))
        self.label_8.setText(_translate("DialogImport", "Separador", None))
        self.cboSep.setItemText(1, _translate("DialogImport", "SPACE", None))
        self.cboSep.setItemText(2, _translate("DialogImport", ",", None))
        self.cboSep.setItemText(3, _translate("DialogImport", ";", None))
        self.label.setText(_translate("DialogImport", "Escolha as colunas para cada tipo de dados:", None))
        self.label_3.setText(_translate("DialogImport", "X:", None))
        self.cboX.setToolTip(_translate("DialogImport", "<html><head/><body><p>Nº Colun -&gt; Coord. X</p></body></html>", None))
        self.label_4.setText(_translate("DialogImport", "Y:", None))
        self.cboY.setToolTip(_translate("DialogImport", "<html><head/><body><p>Nº Colun -&gt; Coord. Y</p></body></html>", None))
        self.label_5.setText(_translate("DialogImport", "Z:", None))
        self.cboZ.setToolTip(_translate("DialogImport", "<html><head/><body><p>Nº Colun -&gt; Prof </p></body></html>", None))
        self.label_6.setText(_translate("DialogImport", "Reflect.:", None))
        self.label_7.setText(_translate("DialogImport", "R:", None))
        self.label_9.setText(_translate("DialogImport", "G:", None))
        self.label_10.setText(_translate("DialogImport", "B:", None))
        self.radioButton_pos.setText(_translate("DialogImport", "Pos", None))
        self.radioButton_neg.setText(_translate("DialogImport", "Neg.", None))
        self.label_23.setText(_translate("DialogImport", "Acesso:", None))
        self.label_12.setText(_translate("DialogImport", "Profundidade: ", None))
        self.lineEdit_Esp.setText(_translate("DialogImport", "0.05", None))
        self.label_13.setText(_translate("DialogImport", "Espaçamento medio (ºLL):", None))
        self.checkBoxLong.setText(_translate("DialogImport", "auto Long W / E", None))
        self.label_21.setText(_translate("DialogImport", "Distribuidor / Organizador:", None))
        self.label_25.setText(_translate("DialogImport", "QC/Obs:", None))
        self.label_20.setText(_translate("DialogImport", "Contacto / Origem :", None))
        self.label_17.setText(_translate("DialogImport", "Resumo:", None))
        self.label_22.setText(_translate("DialogImport", "Tam. MB:", None))
        self.lineEdit_Tamanho.setToolTip(_translate("DialogImport", "<html><head/><body><p>Valor inteiro (Mbytes)</p></body></html>", None))
        self.pushButtonAddEquip.setText(_translate("DialogImport", "Adic. Equipamento", None))
        self.cboDatumVert.setItemText(0, _translate("DialogImport", "Nivel Médio do Mar", None))
        self.cboDatumVert.setItemText(1, _translate("DialogImport", "Zero Hidrográfico", None))
        self.cboDatumVert.setItemText(2, _translate("DialogImport", "Elipsoide WGS84", None))
        self.label_24.setText(_translate("DialogImport", "Cruzeiro:", None))
        self.label_16.setText(_translate("DialogImport", "Data Ini. / Fim:", None))
        self.label_11.setText(_translate("DialogImport", "Datum Horiz / Vert  Orig.:", None))
        self.label_2.setText(_translate("DialogImport", "CDI/CPRD :", None))
        self.label_32.setText(_translate("DialogImport", "Plataforma:", None))
        self.checkBoxProf.setText(_translate("DialogImport", "auto Prof Max / Min", None))
        self.checkBoxLLat.setText(_translate("DialogImport", "auto Lat N / S", None))
        self.pushButtonAddParam.setText(_translate("DialogImport", "Adic. Parametro", None))
        self.sairButton.setText(_translate("DialogImport", "&Cancel", None))
        self.importButton.setText(_translate("DialogImport", "Importar", None))
        self.actionSair.setText(_translate("DialogImport", "sair", None))
        self.actionSair.setToolTip(_translate("DialogImport", "Sair", None))

